// ⚡️ Auto-generated by zap generate

const BASE_URL = "http://localhost:8787";

// --- DB SDK ---
export function useDB<T extends keyof typeof schema>(table: T) {
  return {
    list: async (): Promise<any[]> => {
      return fetch(`${BASE_URL}/db/${table}`).then((res) => res.json());
    },
    insert: async (data: any): Promise<any> => {
      return fetch(`${BASE_URL}/db/${table}`, {
        method: "POST",
        body: JSON.stringify(data),
        headers: { "Content-Type": "application/json" },
      }).then((res) => res.json());
    },
  };
}

// --- Auth SDK ---
export function useAuth() {
  return {
    user: { id: "mock-user", role: "admin" },
    signIn: async () => {},
    signOut: async () => {},
  };
}

// --- API SDK ---
export async function hello(input?: any) {
  const res = await fetch(`${BASE_URL}/hello`, {
    method: "GET",
    headers: { "Content-Type": "application/json" },
  });
  return await res.json();
}

// --- DB Schema (for useDB generic) ---
const schema = {
  user: {
    id: "string",
    name: "string",
  },
} as const;
